spring:
  profiles:
    active: development
    

---
#
# development configuration
#
spring:
   application:
      name: service-registry-server
   config:
      activate:
         on-profile: development

server:
   port: 8761
   
eureka:
   instance:
      hostname: localhost
   server:
      enableSelfPreservation: false
      waitTimeInMsWhenSyncEmpty: 5        
   client:
      fetchRegistry: false
      registerWithEureka: false
      serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

---
#
# production configuration
#
spring:
   application:
      name: service-registry-server
   config:
      activate:
         on-profile: production

server:
   port: 8761
   
eureka:
   instance:
      hostname: 192.168.0.51
   server:
      enableSelfPreservation: false
      waitTimeInMsWhenSyncEmpty: 5        
   client:
      fetchRegistry: false
      registerWithEureka: false
      serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
         


         