spring:
   application:
      name: service-emaillist
   profiles:
      active: development

server:
   port: 0
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true

---
spring:
   config:
      activate:
         on-profile: development
   devtools:
      livereload:
         enabled: true
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.0.51:3307/webdb?characterEncoding=utf8
      username: webdb
      password: webdb   

mybatis:
   config-location: classpath:mybatis/configuration.xml
         
eureka:
   instance:
      preferIpAddress: true
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
         

---
spring:
   config:
      activate:
         on-profile: production
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.0.51:3307/webdb?characterEncoding=utf8
      username: webdb
      password: webdb   

mybatis:
   config-location: classpath:mybatis/configuration.xml
            
eureka:
   instance:
      preferIpAddress: true
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://192.168.0.51:8761/eureka                